### ISSUE TITLE
Plan/start migration from goodtables.io

### ISSUE THREAD

**Issue by roll** [frictionlessdata/repository#10]
# Overview

@sapetti9 Once #6 is done we can start creating issues/PR for goodtables.io users with a recommendation to migrate

**Comment by augusto-herrmann** [comment]
Should there be a *migration guide* of sorts from goodtables.io, especially for repositories containing `goodtables.yml` configurations file? Or is the `.github/frictionless.yaml` file 100% drop-in replacement compatible?

Even if it's not, at least a short note about it in the documentation would be warranted, I think. By searching the site I found [this link](https://repository.frictionlessdata.io/docs/development/migration/#from-goodtables), but it's broken.

**Comment by roll** [comment]
Yes @augusto-herrmann, we will prepare a migration guide

**Comment by roll** [comment]
DONE
