### ISSUE TITLE
Investigate a problem with dataportals.org

### ISSUE THREAD

**Issue by roll** [frictionlessdata/repository#20]
# Overview

https://github.com/okfn/dataportals.org/pull/238#issuecomment-1001087859

**Comment by roll** [comment]
Hi @augusto-herrmann I think https://github.com/okfn/dataportals.org/pull/241 is the fix for the problem

**Comment by augusto-herrmann** [comment]
Thanks, @roll, it works now!

I still don't understand though why the old [failed report](https://repository.frictionlessdata.io/report/?user=okfn&repo=dataportals.org&flow=portals&run=1622883256) shows up blank. It would be useful to have an actionable error message there.
