### ISSUE TITLE
Empty field with required constraint passed the validation

### ISSUE THREAD

**Issue by Andrelamor** [frictionlessdata/repository#21]
# Overview
 The `.csv` file `termos-parceria-contratos-gestao` had pushed with an empty value marked with `required constraint: true` property in [schema](https://github.com/dados-mg/termos-parceria-contratos-gestao/blob/5a4ab3d5c209bf2ea996effeeb0fbe11bdc0516a/schema/termos-parceria-contratos-gestao.json#L115). 

Job #76 on goodtables [had warned about the error](https://goodtables.io/github/dados-mg/termos-parceria-contratos-gestao/jobs/76), but [frictionless within github actions had not](https://github.com/dados-mg/termos-parceria-contratos-gestao/actions/runs/1689372463)

![image](https://user-images.githubusercontent.com/52294411/149834901-0b607771-44e4-422a-852f-0f11ff80e709.png)

**Comment by roll** [comment]
Thanks! I'll investigate

**Comment by roll** [comment]
FIXED by https://github.com/dados-mg/termos-parceria-contratos-gestao/pull/12
