### ISSUE TITLE
Failing validation by zipped resources

### ISSUE THREAD

**Issue by AFoletti** [frictionlessdata/repository#22]
# Overview

I am using the pattern suggested [here ](https://github.com/frictionlessdata/specs/issues/758#issuecomment-986663812) to describe zipped CSVs.

However, the validation fails with an "Encoding Error" (see [here ](https://repository.frictionlessdata.io/report/?user=AFoletti&repo=test_frictionless&flow=ogd10&run=1549365335) for an example report) while the very same datapackage validate the very same files if they are unzipped and referenced one by one.

You can find my datapackages (both the zipped and unzipped resources version) in the attached zip
[datapackages.zip](https://github.com/frictionlessdata/frictionless-py/files/7668340/datapackages.zip)

---

Please preserve this line to notify @roll (lead of this repository)

**Comment by roll** [comment]
Hi @AFoletti,

Sorry for the slow issue handling.

I checked the Python framework and it works fine for a data package like this:

```json
{
  "profile": "data-package",
  "resources": [
        {
          "path": "data.zip",
          "innerpath": "data.csv",
          "format": "csv",
          "name": "data"
        },
        {
          "path": "data.zip",
          "innerpath": "data2.csv",
          "format": "csv",
          "name": "data2"
        }
  ]
}
```

It might be a problem with Frictionless Repository. Do you still experience it?

**Comment by roll** [comment]
```bash
frictionless validate https://www.uvek-gis.admin.ch/BFE/ogd/10/datapackage.json
# -----
# valid: https://www.uvek-gis.admin.ch/BFE/ogd/10/ogd10_energieforschungstatistik_ch.csv
# -----
# -----
# valid: https://www.uvek-gis.admin.ch/BFE/ogd/10/ogd10_energieforschungstatistik_iea.csv
# -----
# -----
# valid: https://www.uvek-gis.admin.ch/BFE/ogd/10/ogd10_catalogs.zip
# -----
# -----
# valid: https://www.uvek-gis.admin.ch/BFE/ogd/10/ogd10_catalogs.zip
# -----
# -----
# valid: https://www.uvek-gis.admin.ch/BFE/ogd/10/ogd10_catalogs.zip
# -----
# -----
# valid: https://www.uvek-gis.admin.ch/BFE/ogd/10/ogd10_catalogs.zip
# -----
# -----
# valid: https://www.uvek-gis.admin.ch/BFE/ogd/10/ogd10_catalogs.zip
# -----
```

**Comment by AFoletti** [comment]
Hello @roll , and thanks for chicking this out.
Actually yes, I still have the same issue. And strangely, the report does not show up anymore 🤔 

I am using the github action for my workflow. You can find [here ](https://github.com/AFoletti/test_frictionless/runs/4877925224?check_suite_focus=true) the action report. Am I doing something blatantly wrong?

**Comment by roll** [comment]
Thank you for the feedback @AFoletti, I'll continue investigating

**Comment by roll** [comment]
Hi @AFoletti,

I created a PR in your repo to resolve the problem which is that Frictionless can't recognize the data package (thinks it's a resource) because it has `datapackage_ZIP.json` file name. We will think about making the error message is more helpful in this case...

Please re-open if it doesn't help

**Comment by roll** [comment]
Here is a CLI demonstration:

```
frictionless validate https://www.uvek-gis.admin.ch/BFE/ogd/staging/datapackage_ZIP.json # ERROR
frictionless validate --type package https://www.uvek-gis.admin.ch/BFE/ogd/staging/datapackage_ZIP.json # VALID
```

**Comment by AFoletti** [comment]
Hi @roll 
Many thanks for your help! That works perfectly
