### ISSUE TITLE
Cannot load a report

### ISSUE THREAD

**Issue by PolykarposPolykarpidis** [frictionlessdata/repository#24]
I am trying to create a Frictionless repo, but I have some problems.
1. I cannot see the report of a failed validation.
![image](https://user-images.githubusercontent.com/61109950/159677305-67e316c4-375f-4afe-9828-35cbf5996bfc.png)

2. I have a question about the action YAML file.
![image](https://user-images.githubusercontent.com/61109950/159679393-2255cd13-b80b-4dfa-bc4f-9f5197597292.png)
What is the meaning of these attributes?

I would appreciate any help. I appreciate any help you can provide.

**Comment by gabrielbdornas** [comment]
@PolykarposPolykarpidis, when this happened in my validations it was just a matter of waiting. I believe the repository needs some time to build the report's components. Try to revisit the report link generated in GitHub action. Is this working now?

**Comment by roll** [comment]
Thanks! I'll investigate

**Comment by roll** [comment]
Hi @PolykarposPolykarpidis,

can you please share the repo you're trying to validate?

**Comment by PolykarposPolykarpidis** [comment]
https://github.com/KDrakoulaki/CompBMus_FAIR

**Comment by roll** [comment]
@gabrielbdornas 
The problem has been fixed.

I'm closing this issue for now. @PolykarposPolykarpidis let us know if you still experience problems (and please share the repo)

**Comment by PolykarposPolykarpidis** [comment]
ok! thank you @roll, I will try again!

**Comment by roll** [comment]
Thanks! Please create a new issue if it still doesn't work as I'm not sure the problem was the same
