### ISSUE TITLE
Goodtables migration guide missing from docs

### ISSUE THREAD

**Issue by augusto-herrmann** [frictionlessdata/repository#26]
# Overview

I think there used to be a migration guide from Goodtables in Frictionless Repository's documentation. Right now, if you open [the docs](https://repository.frictionlessdata.io/docs/introduction) and use the search feature for "Goodtables" you even find a result there.

![search-goodtables](https://user-images.githubusercontent.com/1058414/171405986-831713df-53c2-4af1-8b8a-10c996df0e87.png)

However, when you click on that result you get a "Page not found" error.

For why this is necessary, see #10.

**Comment by lwinfree** [comment]
Good catch, thanks!

**Comment by aivuk** [comment]
@roll I'm reading the instructions about how to run the current validation at https://repository.frictionlessdata.io/docs/getting-started and comparing with the instructions for goodtables at https://github.com/frictionlessdata/goodtables.io/blob/master/docs/configuration/index.md. Are there any major features that doesn't exist in the current validation or something important to tell the users that are going to change from goodtables to the new validation?

**Comment by roll** [comment]
@aivuk 
It's hard to tell in-detail as it's a migration from `goodtables` to `frictionless` with various small changes (usually not related to the most users). Of course, Repository provides much more flexibility as you just basically call the framework underneath

Let's start from the high-level instructions and then iterate on it

**Comment by aivuk** [comment]
I agree with you, I will just give some high level instructions, point to the current documentation and leave a message "Any additional question and if something is not working as expected, please create an issue at X (https://github.com/frictionlessdata/repository/issues/ ?)".

**Comment by roll** [comment]
Yea, I think the most important message is how to move repos to the newer project (Repository)

**Comment by aivuk** [comment]
How about creating an issue (or some other way to contact the users) in the repositories of everyone using goodtables asking to migrate and pointing to the migration documentation? I can check at googtables.io database how many users we have.

**Comment by augusto-herrmann** [comment]
These PRs have been used to migrate some repositories from GoodTables to f11d Repository. If you look at the diffs it might help in writing the migration guide:

* [okfn/dataportals.org](/okfn/dataportals.org/pull/238)
* [okfn/publicbodies](/okfn/publicbodies/pull/142)
* [augusto-herrmann/transparencia-dados-abertos-brasil](/augusto-herrmann/transparencia-dados-abertos-brasil/pull/29)
