### ISSUE TITLE
Error: Cannot validate inquiry: stdout maxBuffer length exceeded

### ISSUE THREAD

**Issue by jbothma** [frictionlessdata/repository#28]
# Overview

Hi! I'm getting

> Error: Cannot validate inquiry: stdout maxBuffer length exceeded

when running as a github action.

![Screenshot_2022-07-06_23-02-54](https://user-images.githubusercontent.com/235801/177642692-1af8163e-f053-4016-9de2-231ce5e39408.png)

https://github.com/vulekamali/budget-spending-data/blob/987ce9308e316e6fe8570500473757a4ccf346a3/.github/workflows/frictionless.yml
https://github.com/vulekamali/budget-spending-data/blob/987ce9308e316e6fe8570500473757a4ccf346a3/.github/frictionless.yml

Seems to be coming from here https://github.com/frictionlessdata/repository/blob/5ad6a7b66627b76220872a47054d5c291db95913/lib/action.js#L77

https://frictionlessdata.slack.com/archives/C0362US1U3G/p1657011118812489

**Comment by shashigharti** [comment]
Thank you for reporting! We will look into it.

**Comment by roll** [comment]
SPLIT into:
- https://github.com/vulekamali/budget-spending-data/pull/3
- https://github.com/frictionlessdata/repository/issues/31
