### ISSUE TITLE
Custom input

### ISSUE THREAD

**Issue by naanrdk** [frictionlessdata/repository#34]
# Overview

In continuation conversation with @roll, replacing [path](https://github.com/frictionlessdata/repository/pull/14#discussion_r928522858)
Wanting to give custom input for validating

[Full S3 bug report](https://github.com/naanrdk/frictionless/runs/7493260275?check_suite_focus=true)

**Comment by roll** [comment]
@shashigharti can you please take a look?

**Comment by shashigharti** [comment]
@naanrdk I am not able to access the link Full S3 bug report. Could you please share the screenshot.

**Comment by naanrdk** [comment]
@shashigharti, attached 
![image](https://user-images.githubusercontent.com/13908439/181168817-cc0df401-b1e9-4b4b-8f29-f69ba03468bf.png)
Dataset link: https://dev-data.s3.wasabisys.com/apy/processed/apy.csv?AWSAccessKeyId=HB3LLH7JRZCFQI2OCM2Y&Expires=1658725193&Signature=EFS1jsT%2Bjtt3%2Bf9Huhlu3ooo6kA%3D

**Comment by shashigharti** [comment]
Hi naanrdk,

I can't access the link you are sharing "https://dev-data.s3.wasabisys.com/apy/processed/apy.csv?AWSAccessKeyId=HB3LLH7JRZCFQI2OCM2Y&Expires=1658910131&Signature=PMZ5MlIxnMlPkOOWZ7H1mg2bVD8%3D"

Looks like you are trying to use repository with private data from s3 and getting this error?.

**Comment by naanrdk** [comment]
@shashigharti, apologies, as it as private data from s3 the pre signed url was only valid for certain amount of time, I've regenerated for your reference:
https://dev-data.s3.wasabisys.com/apy/processed/apy.csv?AWSAccessKeyId=HB3LLH7JRZCFQI2OCM2Y&Expires=1658939165&Signature=4lBqrXSgxmtOVxzTwGYQU%2BxXimc%3D

**Comment by shashigharti** [comment]
@naanrdk I tried running the action using file from s3 bucket(by making it public). It works fine
yaml: https://github.com/shashigharti/currency-codes/blob/master/.github/workflows/frictionless.yaml
report: https://repository.frictionlessdata.io/report/?user=shashigharti&repo=currency-codes&flow=frictionless&run=2752915254
path: https://github.com/shashigharti/currency-codes/blob/master/datapackage.json

@roll If the files are private, the s3 bucket has to be made available in the docker container. If not this error occurs:
![error](https://user-images.githubusercontent.com/5582809/181485543-f1ceb777-3c2d-47d2-bd18-1a0aac833955.png)
and we might also need to update this file to include 's3', in that case.
https://github.com/frictionlessdata/repository/blob/main/requirements.txt

**Comment by naanrdk** [comment]
@shashigharti, I see that you have forked rolls repo I don't find the lib folder in it how did you run the action also you have used codes-all.csv as input the data from the repository itself can the input path be set dynamically as an argument instead of hard coding it?

**Comment by shashigharti** [comment]
All the details of running the validations are here: https://www.youtube.com/watch?v=kXA4hmuF57c

**Comment by shashigharti** [comment]
And I haven't forked repository folder. It is a different repo that I forked and used the repository as github actions. The data that I am using is from s3 bucket(that I uploaded). . I have removed data folder as well from the repo.
https://github.com/shashigharti/currency-codes

**Comment by naanrdk** [comment]
@shashigharti, I was under impression that the s3 has to be specified in the https://github.com/frictionlessdata/repository/pull/14#discussion_r928515825 (frictionless.yaml) and according to the YouTube and you have used the s3 path in the https://github.com/shashigharti/currency-codes/blob/master/datapackage.json I got confused.

**Comment by shashigharti** [comment]
> I was under impression that the s3 has to be specified in the [#14 (comment)](https://github.com/frictionlessdata/repository/pull/14#discussion_r928515825) (frictionless.yaml) and according to the YouTube but you have used the s3 path in the https://github.com/shashigharti/currency-codes/blob/master/datapackage.json I got confused.

@naanrdk you can use it in many different ways, example of using a different configuration instead of 'datapackage.json', you can find it here:
https://youtu.be/kXA4hmuF57c?t=584

And this documentation explains it as well:
https://repository.frictionlessdata.io/docs/configuration

I have also made changes to the following repo adding frictionless.yaml file, it then uses frictionless.yaml instead of 'datapackage.json' which is detected automatically
https://github.com/shashigharti/currency-codes

**Comment by naanrdk** [comment]
Thanks @shashigharti with regards to using a private s3 is not functional yet?

**Comment by shashigharti** [comment]
yes it doesn't support private buckets for security reasons so one way would be to fork the repository 'repo' and publish github action 
repo to fork: https://github.com/frictionlessdata/repository
publishing github action: https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace

you can then make changes to your forked repo (github action) and use it whereever you want to validate your data.

**Comment by roll** [comment]
@naanrdk 
I agree with @shashigharti that you might achieve it using Frictionless Framework (install python/install frictionless/validate) using it here directly - https://github.com/shashigharti/currency-codes/blob/ef6ec595b58ef1b634725f5001d059791beb2739/.github/workflows/general.yaml#L22 - and providing AWS secrets as github secrets / env vars

Another question is that it's highly unrecommented to do so as it's a security risk. I would suggest you just make your bucket public as if you anyway expose it to Github Action it's de-facto public

**Comment by naanrdk** [comment]
@roll I want to use this on a private bucket but for testing purpose I was rudimentary giving the presigned URL to test. Understood shall try the framework way!

**Comment by naanrdk** [comment]
Unable to validate the data from S3 with framework:
![image](https://user-images.githubusercontent.com/13908439/182578403-1da0579e-6323-41af-a2e9-65074fc2db68.png)

**Comment by roll** [comment]
Hi @naanrdk, you don't need to read the data manually before validate. Pelase take a look - https://framework.frictionlessdata.io/docs/tutorials/schemes/s3-tutorial
