### ISSUE TITLE
Spaces in a workflow name breaks the link to the report

### ISSUE THREAD

**Issue by roll** [frictionlessdata/repository#37]
# Overview

- https://github.com/augusto-herrmann/transparencia-dados-abertos-brasil/actions/runs/3998640675/jobs/6861546674
- https://github.com/augusto-herrmann/transparencia-dados-abertos-brasil/pull/82/files

**Comment by roll** [comment]
Hi @augusto-herrmann,

It should be fixed now

**Comment by augusto-herrmann** [comment]
Thanks, @roll!
