### ISSUE TITLE
Broken links to resources in validation report

### ISSUE THREAD

**Issue by ezwelty** [frictionlessdata/repository#40]
The names of the CSV files are clickable in the validation report. However, these links are broken. For example, the report for 
 the demo repository:

https://repository.frictionlessdata.io/pages/dashboard.html?user=frictionlessdata&repo=repository-demo&flow=frictionless

Links to `data/valid.csv`: https://repository.frictionlessdata.io/pages/data/valid.csv

![image](https://user-images.githubusercontent.com/377523/218456618-f6351b9b-4171-47be-b968-913fb15b0405.png)

**Comment by roll** [comment]
Thanks @ezwelty,

I have to disable links for now #40
