### ISSUE TITLE
Release stable v1

### ISSUE THREAD

**Issue by roll** [frictionlessdata/repository#6]
# Overview

We need to gather feedback for 1-2 month and then release.

**Comment by gabrielbdornas** [comment]
Hy @roll, one more time, congratulation on this work! I wonder if you could help me with one question about the validation it's been done here. I suspect that the actual validation is only in the data files and not using datapackages.json, am I right?

I'm using a simple dataset as an example ([github repo](https://github.com/dados-mg/datapackage-reprex/tree/frictionless-github-continuos-validation)) where locally "frictionless validate data/letters-vowels.csv" and "frictionless validate data/letters-consonants.csv" work just fine but "frictionless validate datapackage.json" fails (purposely), as you can see in the picture below:

![Screenshot from 2021-06-24 12-51-22](https://user-images.githubusercontent.com/49699290/123294116-ee470680-d4ea-11eb-9707-a3fb61d93b18.png)

Despite this "datapackage" error, everything works fine on the GitHub action continuos validation, as you can see below:

![Screenshot from 2021-06-24 12-56-18](https://user-images.githubusercontent.com/49699290/123294831-94930c00-d4eb-11eb-932d-18ba7aecfa7e.png)
 
Am I right in my guessing that validations against datapackages.json aren't yet available?

**Comment by roll** [comment]
Hi @gabrielbdornas, and thanks!

Frictionless Repository just passes the validation inquiry to Frictionless Framework so it should be possible to do any validations you can do with the framework.

Here is a configuration docs - https://repository.frictionlessdata.io/docs/configuration

In you case, it should work if you add this configuration file:

> .github/frictionless.yaml (not that it's not in the workflows it's a new file)

```
main:
  tasks:
    - source: datapackage.json
```

**Comment by roll** [comment]
@gabrielbdornas 
Since `v0.14` it detects data packages automatically using this glob - https://github.com/frictionlessdata/repository/blob/main/lib/config.js#L6

**Comment by roll** [comment]
DONE in de6d5b0
